name       : tinc
version    : 1.0.31
release    : 1
source     :
    - https://www.tinc-vpn.org/packages/tinc-1.0.31.tar.gz : d3cbc82e6e07975a2ccc0b369d07e30fc3324e71e240dca8781ce9a4f629519b
license    : GPL-2.0
component  : network.clients
summary    : tinc is a Virtual Private Network (VPN) daemon that uses tunnelling and encryption to create a secure private network between hosts on the Internet.
description: |
    tinc is a Virtual Private Network (VPN) daemon that uses tunnelling and encryption to create a secure private network between hosts on the Internet.
builddeps  :
    - lzo-devel
setup      : |
    %reconfigure
build      : |
    %make
install    : |
    %make_install
