name       : tinc
version    : 1.0.35
release    : 2
source     :
    - https://www.tinc-vpn.org/packages/tinc-1.0.35.tar.gz : 18c83b147cc3e2133a7ac2543eeb014d52070de01c7474287d3ccecc9b16895e
license    : GPL-2.0
component  : network.clients
summary    : tinc is a Virtual Private Network (VPN) daemon that uses tunnelling and encryption to create a secure private network between hosts on the Internet.
description: |
    tinc is a Virtual Private Network (VPN) daemon that uses tunnelling and encryption to create a secure private network between hosts on the Internet.
builddeps  :
    - lzo-devel
setup      : |
    %reconfigure
build      : |
    %make
install    : |
    %make_install
